services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - redis-network

  rediscacheapi:
    image: rediscacheapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:80"
      - "5002:443"
    depends_on:
      - redis
    networks:
      - redis-network

networks:
  redis-network: