# This is a generated file. Not intended for manual editing.
services:
  rediscacheapi:
    build:
      context: "/Users/kenny/code/redis-practice/RedisCacheApi"
      dockerfile: "Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-arm64/dotnet/dotnet"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "rediscacheapi:dev"
    ports:
    - "127.0.0.1:57010:57100"
    - "127.0.0.1:57210:57300"
    volumes:
    - "/Users/kenny/.nuget/packages:/root/.nuget/packages"
    - "/Users/kenny/code/redis-practice/RedisCacheApi:/app:rw"
    - "/Users/kenny/code/redis-practice/RedisCacheApi:/src:rw"
    - "/Users/kenny/.local/share/JetBrains/RiderRemoteDebugger/2023.3.2/LinuxArm64:/opt/rider-debugger"
    - "/Applications/Rider.app/Contents/bin:/etc/opt/rider-debugger/backend-log.xml"
    - "/Users/kenny/Library/Logs/JetBrains/Rider2023.3/DebuggerWorker/JetBrains.Debugger.Worker.2024_2_02_13_27_13:/var/opt/rider-debugger:rw"
    working_dir: "/app"
